### PR TITLE
[API] get_node_info

### LINKED ISSUE #62: API - get node info
## Description

Communicates with node API: `GET /api/v1/info`

http status code 200:
```
{
  "data": {
    "name": "HORNET",
    "version": "0.5.3",
    "isHealthy": false,
    "networkId": "alphanet1",
    "latestMilestoneIndex": 106264,
    "solidMilestoneIndex": 106264,
    "pruningIndex": 0,
    "features": [
      "PoW"
    ]
  }
}
```

## Motivation

Get node info via HTTP API.

## Requirements

1. parses JSON
2. returns populated `res_node_info_t`

## Are you planning to do it yourself in a pull request?

Yes

### LINKED ISSUE #76: API - potential memory leaks
## Bug description

```c
iota_str_t *cmd = iota_str_new(conf->url);
if (cmd == NULL) {
 ...
  return -1;
}

if (iota_str_append(cmd, cmd_info)) {
  ...
  return -1;
}
```

The snippet could cause memory leaks at runtime. if `iota_str_append` returns an error.
this scenario could be found in RESTful API implementations.
- [x] get_health
- [x] get_message_by_id
- [ ] get_node_info
- [x] get_output
- [x] get_outputs_from_address
- [x] get_tips

### PR DESCRIPTION
**Pull request by bernardoaraujor**
# Description of change

add `get_node_info` API call
solve #62 + #76

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

[tests/client/api_v1/test_get_info.c](https://github.com/bernardoaraujor/iota.c/blob/dev_get_node_info/tests/client/api_v1/test_get_info.c)

- test null cases
- test deser
- many tests are commented out because depends on endpoint

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests using Unity that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bernardoaraujor** [comment]
draft because not sure how to handle features
check https://github.com/bernardoaraujor/iota.c/blob/63ef887502ff495c5ec86aff47914a54e5104fb0/src/client/api/v1/get_node_info.c#L168

File: src/client/api/v1/get_node_info.c [hunk 1]
```diff
@@ -147,6 +147,13 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
       ret = -1;
       goto end;
     }
+
+    // TODO: gets features
+    // if ((ret = json_string_array_to_utarray(data_obj, key_features, res->u.output_node_info->features)) != 0) {
```
Comment (bernardoaraujor) [inline src/client/api/v1/get_node_info.c]: @oopsmonk how do you suggest to implement this?
your original implementation uses `char features[128]`, however how do we handle multiple features?
is `utarray` a good approach, or am I missing something from the `char` array approach?

Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: the `res_node_info_t` is outdated. utarray can be used instead of char array.

**Review by bernardoaraujor — COMMENTED** [review]
self review ok

File: src/client/api/v1/get_node_info.c [hunk 2]
```diff
@@ -56,9 +86,7 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
   char const *const key_version = "version";
   char const *const key_healthy = "isHealthy";
   char const *const key_net = "networkId";
-  char const *const key_lm = "latestMilestoneId";
   char const *const key_lm_index = "latestMilestoneIndex";
-  char const *const key_sm = "solidMilestoneId";
   char const *const key_sm_index = "solidMilestoneIndex";
   char const *const key_pruning = "pruningIndex";
   char const *const key_features = "features";
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c:123]: `minPowScore` is missing

File: src/client/api/v1/get_node_info.c [hunk 3]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+  }
 
   cJSON *data_obj = cJSON_GetObjectItemCaseSensitive(json_obj, key_data);
   if (data_obj) {
     // gets name
-    if ((ret = json_get_string(data_obj, key_name, res->name, sizeof(res->name))) != 0) {
+    if ((ret = json_get_string(data_obj, key_name, res->u.output_node_info->name,
+                               sizeof(res->u.output_node_info->name))) != 0) {
       printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_name);
       ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: assigning `ret` is no needed, same as the following `if` conditions.

File: src/client/api/v1/get_node_info.c [hunk 4]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
       goto end;
     }
 
     // gets version
-    if ((ret = json_get_string(data_obj, key_version, res->version, sizeof(res->version))) != 0) {
+    if ((ret = json_get_string(data_obj, key_version, res->u.output_node_info->version,
+                               sizeof(res->u.output_node_info->version))) != 0) {
       printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_version);
       ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 5]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
       goto end;
     }
 
-    if ((ret = json_get_boolean(data_obj, key_healthy, &res->is_healthy)) != 0) {
+    // gets isHealthy
+    if ((ret = json_get_boolean(data_obj, key_healthy, &res->u.output_node_info->is_healthy)) != 0) {
       printf("[%s:%d]: gets %s json boolean failed\n", __func__, __LINE__, key_healthy);
       ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 6]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
       goto end;
     }
 
-    // TODO
+    // gets networkId
+    if ((ret = json_get_string(data_obj, key_net, res->u.output_node_info->network_id,
+                               sizeof(res->u.output_node_info->network_id))) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_net);
+      ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 7]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+      goto end;
+    }
+
+    // gets latestMilestoneIndex
+    if ((ret = json_get_uint64(data_obj, key_lm_index, &res->u.output_node_info->latest_milestone_index)) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_lm_index);
+      ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 8]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+      goto end;
+    }
+
+    // gets solidMilestoneIndex
+    if ((ret = json_get_uint64(data_obj, key_sm_index, &res->u.output_node_info->solid_milestone_index)) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_sm_index);
+      ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 9]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+      goto end;
+    }
+
+    // gets pruningIndex
+    if ((ret = json_get_uint64(data_obj, key_pruning, &res->u.output_node_info->pruning_milestone_index)) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_pruning);
+      ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 10]
```diff
@@ -68,36 +96,82 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+      goto end;
+    }
+
+    utarray_new(res->u.output_node_info->features, &ut_str_icd);
+    if ((ret = json_string_array_to_utarray(data_obj, key_features, res->u.output_node_info->features)) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_features);
+      ret = -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: diito

File: src/client/api/v1/get_node_info.c [hunk 11]
```diff
@@ -6,9 +6,33 @@
 #include "client/network/http.h"
 #include "core/utils/iota_str.h"
 
+res_node_info_t *res_node_info_new() {
+  res_node_info_t *res = malloc(sizeof(res_node_info_t));
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c:10]: `res` needs validation.

File: src/client/api/v1/get_node_info.c [hunk 12]
```diff
@@ -6,9 +6,33 @@
...
+  res->is_error = false;
+  return res;
+}
+
+void res_node_info_free(res_node_info_t *res) {
+  if (res) {
+    if (res->is_error) {
+      res_err_free(res->u.error);
+    } else {
+      if (res->u.output_node_info->features) utarray_free(res->u.output_node_info->features);
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: please use curly brackets

File: tests/client/api_v1/test_get_info.c [hunk 13]
```diff
@@ -1,34 +1,66 @@
...
+  TEST_ASSERT_EQUAL_STRING("HORNET", info->u.output_node_info->name);
+  TEST_ASSERT_EQUAL_STRING("0.6.0-alpha", info->u.output_node_info->version);
+  TEST_ASSERT_TRUE(info->u.output_node_info->is_healthy);
+  TEST_ASSERT_EQUAL_STRING("alphanet1", info->u.output_node_info->network_id);
+  TEST_ASSERT_EQUAL_UINT64(82847, info->u.output_node_info->latest_milestone_index);
+  TEST_ASSERT_EQUAL_UINT64(82847, info->u.output_node_info->solid_milestone_index);
+  TEST_ASSERT_EQUAL_UINT64(82325, info->u.output_node_info->pruning_milestone_index);
+  char** p;
+  p = NULL;
+  p = (char**)utarray_next(info->u.output_node_info->features, p);
```
Comment (oopsmonk) [inline tests/client/api_v1/test_get_info.c]: it's not easy to understand for API users, please provide a method for accessing `features`.

**Review by oopsmonk — CHANGES_REQUESTED** [review]

File: tests/client/api_v1/test_get_info.c (hunk 13 above)
Comment (bernardoaraujor) [reply tests/client/api_v1/test_get_info.c]: done.
I think there are many ways to implement this. Not sure if I did the best way.

File: src/client/api/v1/get_node_info.c [hunk 14]
```diff
@@ -6,9 +6,72 @@
 #include "client/network/http.h"
 #include "core/utils/iota_str.h"
 
+res_node_info_t *res_node_info_new() {
+  res_node_info_t *res = malloc(sizeof(res_node_info_t));
+  if (res == NULL) {
+    printf("[%s:%d]: OOM\n", __func__, __LINE__);
+    return -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: incompatible return value.

File: src/client/api/v1/get_node_info.c (hunk 3 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c (hunk 4 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c (hunk 5 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c (hunk 7 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c [hunk 15]
```diff
@@ -68,36 +136,89 @@ int deser_node_info(char const *const j_str, res_node_info_t *res) {
...
+    // gets networkId
+    if ((ret = json_get_string(data_obj, key_net, res->u.output_node_info->network_id,
+                               sizeof(res->u.output_node_info->network_id))) != 0) {
+      printf("[%s:%d]: gets %s json string failed\n", __func__, __LINE__, key_net);
+      ret = -1;
+      goto end;
+    }
+
+    // gets minPowScore
+    if ((json_get_uint64(data_obj, key_min_pow_score, &res->u.output_node_info->minPowScore)) != 0) {
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c (hunk 9 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.c (hunk 10 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: extra brackets. why not take the json_get_string returning value as `ret`?

File: src/client/api/v1/get_node_info.h [hunk 16]
```diff
@@ -12,18 +14,44 @@ typedef struct {
   char name[32];
   char version[32];
   bool is_healthy;
-  uint8_t network_id;
-  byte_t latest_milestone_id[32];
+  char network_id[32];
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.h:17]: is network Id fit in 32 bytes string? how many bytes of the network ID string in node API?

File: src/client/api/v1/get_node_info.h [hunk 17]
```diff
@@ -12,18 +14,44 @@ typedef struct {
...
+  uint64_t minPowScore;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.h]: snake_case

File: src/client/api/v1/get_node_info.c [hunk 18]
```diff
@@ -6,9 +6,72 @@
...
+        utarray_free(res->u.output_node_info->features);
+      }
+      free(res->u.output_node_info);
+    }
+    free(res);
+  }
+}
+
+char **get_features(res_node_info_t *info) {
+  int len = utarray_len(info->u.output_node_info->features);
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: `info` could be a NULL.
don't need extra memory to store feature strings, here is a good example of this function.
https://github.com/iotaledger/iota.c/blob/master/cclient/response/get_node_info.h#L269

**Review by oopsmonk — CHANGES_REQUESTED** [review]
spending extra memory to store feature strings is unnecessary. please refer to the example in comments.

File: src/client/api/v1/get_node_info.h (hunk 16 above)
Comment (bernardoaraujor) [reply src/client/api/v1/get_node_info.h:17]: I based this solution on the response for `info` from a Chrysalis node:
```
{"data":{"name":"HORNET","version":"0.6.0-alpha","isHealthy":true,"networkId":"alphanet1","minPowScore":4000,"latestMilestoneIndex":226119,"solidMilestoneIndex":226119,"pruningIndex":0,"features":["PoW"]}}
```

there, `networkID` is a string.
however, it was declared as a `uint32` on the `protobuf` layout: https://github.com/iotaledger/hive.go/blob/db5fe673cf0378aceb06a83cc9183a4441c20656/autopeering/discover/proto/message.pb.go#L37

here's `getNetworkID`:
https://github.com/iotaledger/hive.go/blob/db5fe673cf0378aceb06a83cc9183a4441c20656/autopeering/discover/proto/message.pb.go#L87

so I'm missing where it turns from `uint32` into string... perhaps it's my poor knowledge on `protobuf`?

Comment (oopsmonk) [reply src/client/api/v1/get_node_info.h:17]: it's an arbitrary string passed via the command line when launching Hornet.

File: src/client/api/v1/get_node_info.c [hunk 19]
```diff
@@ -6,9 +6,63 @@
...
+    return NULL;
+  }
+
+  int len = utarray_len(info->u.output_node_info->features);
+  if (idx < 0 || idx >= len) {
+    printf("[%s:%d]: get_features failed (invalid index)\n", __func__, __LINE__);
+    return NULL;
+  }
+
+  return *(const char **)utarray_eltptr(info->u.output_node_info->features, idx);
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]:
```
../src/client/api/v1/get_node_info.c:45:10: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  return *(const char **)utarray_eltptr(info->u.output_node_info->features, idx);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: src/client/api/v1/get_node_info.c [hunk 20]
```diff
@@ -6,9 +6,63 @@
...
+}
+
+size_t get_node_features_num(res_node_info_t *info) {
+  if (info == NULL) {
+    printf("[%s:%d]: get_features failed (null parameter)\n", __func__, __LINE__);
+    return NULL;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]:
```
../src/client/api/v1/get_node_info.c:51:12: warning: incompatible pointer to integer conversion returning 'void *' from a function with result type 'size_t' (aka 'unsigned long') [-Wint-conversion]
    return NULL;
           ^~~~
```

**Review by oopsmonk — CHANGES_REQUESTED** [review]
please fix warnings in comments and https://github.com/iotaledger/iota.c/runs/1646073872#step:6:952

File: src/client/api/v1/get_node_info.h (hunk 16 above)
Comment (bernardoaraujor) [reply src/client/api/v1/get_node_info.h:17]: so is ok to use array of 32 char?

File: src/client/api/v1/get_node_info.c (hunk 20 above)
Comment (bernardoaraujor) [reply src/client/api/v1/get_node_info.c]: could you clarify what you meant [here](https://github.com/iotaledger/iota.c/pull/78#discussion_r551138678)?

It was unclear to me what you meant, so I assumed you confused *bracket* with *parenthesis*.
I removed the extra parenthesis, but it generated the following:

[`warning: using the result of an assignment as a condition without parentheses`](https://github.com/iotaledger/iota.c/runs/1646073872#step:6:952)

File: src/client/api/v1/get_node_info.h (hunk 16 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.h:17]: I think it should be okay. be care of buffer overflow if the string is longer than 32 bytes.

File: src/client/api/v1/get_node_info.c (hunk 20 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.c]: sorry, you are right, it's parentheses.

File: src/client/api/v1/get_node_info.c [hunk 21]
```diff
@@ -6,9 +6,63 @@
...
+  }
+
+  return *(char **)utarray_eltptr(info->u.output_node_info->features, idx);
+}
+
+size_t get_node_features_num(res_node_info_t *info) {
+  if (info == NULL) {
+    printf("[%s:%d]: get_features failed (null parameter)\n", __func__, __LINE__);
+    return -1;
```
Comment (oopsmonk) [inline src/client/api/v1/get_node_info.c]: the return type is size_t which is unsigned.

**Review by oopsmonk — CHANGES_REQUESTED** [review]

File: src/client/api/v1/get_node_info.h (hunk 16 above)
Comment (bernardoaraujor) [reply src/client/api/v1/get_node_info.h:17]: I'm checking with the HORNET team to be 100% sure.

Comment (bernardoaraujor) [reply src/client/api/v1/get_node_info.h:17]: the integer representation is a `blake2b` hash of the input string.
you can check the function [here](https://github.com/iotaledger/iota.go/blob/43ffdd479925a3120ce44a6f2701db5294c74779/protocol.go#L13)

apparently there's no upper character limit for the `networkId` string.

I checked the `json_get_string` implementation.
It calls `strncpy` [here](https://github.com/iotaledger/iota.c/blob/e7b8327284db33179a5127842e68c656437398cb/src/client/api/json_utils.c#L22)

I did a test with 33 chars as input (`networkId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab`), it just ignores the 33rd character, so I guess there's no danger of buffer overflow.

**Review by oopsmonk — APPROVED** [review]
lgfm

File: src/client/api/v1/get_node_info.h (hunk 16 above)
Comment (oopsmonk) [reply src/client/api/v1/get_node_info.h:17]: the hash of Network ID is part of the protocol, it's not related to this API.
imo, if the network ID string is longer than 32 bytes it will be cut into a 32-byte-string which is unexpected behavior from the users' point of view.
