### PR TITLE
API changes on iota_client_get_inclusion_states and iota_client_get_balances

### LINKED ISSUE #22: getBalances will no longer require a threshold
### Bug description
In this [PR](https://github.com/iotaledger/iri/pull/1768#pullrequestreview-365391016), the `threshold` parameter is removed from the getBalances endpoint on IRI nodes.

Currently, this is a required parameter is the library, so we should make it optional.

### Expected behaviour
The `threshold` parameter is optional (for backwards compatibility)

### Actual behavior
The `threshold` parameter is required

### Am I planning to do it myself with a PR?
No.

### PR DESCRIPTION
**Pull request by oopsmonk**
# Description of change

Fix #22 
With regard to IRI 1.8.6
* threshold is deprecated in get_balances 
* the tips is deprecated in get_inclusion_states.

## Type of change

- Bug fix 

## How the change has been tested

local test with IRI1.8.6 and Hornet nodes.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests using ginkgo that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: cclient/api/examples/example_get_transactions_to_approve.c [hunk 1]
```diff
@@ -7,8 +7,8 @@
 
 #include "cclient/api/examples/cclient_examples.h"
 
-static tryte_t const *const REF_HASH =
-    (tryte_t *)"VOPPIXFBHNNEFAAZJLLKTTFMMVJZPHQCTROSU99KYHYBGLJYMCPGIQGSUW9NQQ9TOVTEOKFDCAJLXA999";
+// static tryte_t const *const REF_HASH =
```
Comment (wusyong) [inline cclient/api/examples/example_get_transactions_to_approve.c:10]: Why not just remove them?

File: cclient/api/tests/test_find_transactions.c [hunk 2]
```diff
@@ -48,6 +48,7 @@ static void test_find_tx_by_bundle(void) {
   TEST_ASSERT_NULL(find_tx_res);
 }
 
+/*
```
Comment (wusyong) [inline cclient/api/tests/test_find_transactions.c:51]: Ditto

File: cclient/api/examples/example_get_transactions_to_approve.c (hunk 1 above)
Comment (oopsmonk) [reply cclient/api/examples/example_get_transactions_to_approve.c:10]: this is an example that showing people how to use this API.

File: cclient/api/tests/test_find_transactions.c (hunk 2 above)
Comment (oopsmonk) [reply cclient/api/tests/test_find_transactions.c:51]: will do, after IRI 1.8.5 die. :P

**Review by wusyong — APPROVED** [review]
